// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAasCp60RcXxi4VHVc-eGbk-xFum2OrIfQ',
    appId: '1:482290448414:web:70bf0bed65ecfe22ccd60f',
    messagingSenderId: '482290448414',
    projectId: 'halaqa-quran',
    authDomain: 'halaqa-quran.firebaseapp.com',
    storageBucket: 'halaqa-quran.appspot.com',
    measurementId: 'G-9CQETY5XD7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFvRekGWfV7xuJpixNdxE9Lr-cPgCujkk',
    appId: '1:482290448414:android:50469ea815b4508eccd60f',
    messagingSenderId: '482290448414',
    projectId: 'halaqa-quran',
    storageBucket: 'halaqa-quran.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcb_wOAw1zbGxSMWdUiskwIWQIg4OIUw8',
    appId: '1:482290448414:ios:be65b3e0551c3307ccd60f',
    messagingSenderId: '482290448414',
    projectId: 'halaqa-quran',
    storageBucket: 'halaqa-quran.appspot.com',
    iosBundleId: 'com.example.halqahquran',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcb_wOAw1zbGxSMWdUiskwIWQIg4OIUw8',
    appId: '1:482290448414:ios:be65b3e0551c3307ccd60f',
    messagingSenderId: '482290448414',
    projectId: 'halaqa-quran',
    storageBucket: 'halaqa-quran.appspot.com',
    iosBundleId: 'com.example.halqahquran',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAasCp60RcXxi4VHVc-eGbk-xFum2OrIfQ',
    appId: '1:482290448414:web:418f28c28b0f6ab1ccd60f',
    messagingSenderId: '482290448414',
    projectId: 'halaqa-quran',
    authDomain: 'halaqa-quran.firebaseapp.com',
    storageBucket: 'halaqa-quran.appspot.com',
    measurementId: 'G-EQSLM8JP0H',
  );
}
